enum Type {
  SEMINAR
  LECTURE
  LAB
}
enum Weekday{
  MONDAY
  TUESDAY
  WEDNESDAY
  THURSDAY
  FRIDAY
}
type Activity {
  group: Int
  room: String
  subject: String
  teachers: [String!]!
  students: [String!]!
  weekday: Weekday
  startTime: Int
  endTime: Int
  type: Type
}
type Query {
  activities(studentsId: Int!, weekday: [Weekday!], group: [Int!], type: [Type!]): [Activity!]!
}